### ISSUE TITLE
MIDI DIN not work

### ISSUE THREAD

**Issue by prostealth** [alf45tar/PedalinoMini#158]
im just build pedalinomini usb and wifi works but MIDI out DIN port doesnt work.. does i need to make MIDI IN port too so it will work?

**Comment by alf45tar** [comment]
No, you don't. MIDI IN is optional.
I suggest to check the wiring and check if the port is enabled in the WEB UI under Interfaces.

**Comment by yush** [comment]
Hello,
I'm trying to use legacy MIDI out with no success too.
The wiring is OK, because I tried with a simple Arduino sketch. Moreover, I realised the optionnal part on the MIDI out schematics the LED is not blinking when a MIDI command is sent (I see it through the serial monitor). I also checked that the GPIO 4 is working with another simple Arduino sketch.

**Comment by alf45tar** [comment]
I suppose MIDI OUT is enabled

![Screenshot 2020-12-11 at 18 39 12](https://user-images.githubusercontent.com/35426671/101935991-37370d80-3be0-11eb-8962-167148b8fddf.png)

Please attach a photo of your circuit.

**Comment by alf45tar** [comment]
@yush did you solved?

**Comment by yush** [comment]
Yes it works ! 
Sorry for the delay, the end of the year was quite busy. I tried again yesterday, and it works. I think my previous circuit was buggy.

Thank you very much for the support and the work you do on this project.
