### ISSUE TITLE
Support for esp-wrover-kit?

### ISSUE THREAD

**Issue by nuclearxstudios** [alf45tar/PedalinoMini#242]
Hi are there any plans for esp-wrover-kit?

One of the boards using this is the TTGO T-Koala

**Comment by alf45tar** [comment]
esp-wrover-kit is not currently in the plan because is too expensive. Apart the display it could also works as a standard esp32 board.
TTGO T-Koala http://www.lilygo.cn/prod_view.aspx?TypeId=50033&Id=1125&FId=t3:50033:3 is not a wrover-kit. I think the T-Display is better. Hower again it could also works as any generic esp32 board with a minimal changes (may be just pin remapping)..

**Comment by nuclearxstudios** [comment]
Thanks, also yeah it works as a standard esp32 board.

I had to add the wrover-kit as the board for the t-koala
