### ISSUE TITLE
Single Press / Long Press Confusion

### ISSUE THREAD

**Issue by marosell** [alf45tar/PedalinoMini#34]
Two issues I have discovered. To test, I have a Momentary Pedal on Pedal#4 set as Control Change. 

1. When Single Press and Long Press are both enabled, both use the Long Press "MIDI Value 3", rather than Single Press using "MIDI Value 1" and Long Press using "MIDI Value 3"

2. I have disabled Single Press. Single Press is not disabled, and still sends "MIDI Value 3"

**Comment by alf45tar** [comment]
Thank for your debugging.

I think the issue is a little bit different. By default single press should be very fast otherwise it is recognized as long press.

The issue is that double press and long press are enabled together. They cannot be disabled one by one.

I let you know when fixed.

**Comment by alf45tar** [comment]
Fixed. 
Let me know if it is ok for you.

**Comment by mknerr** [comment]
I seem to be having issues as well, and I am using the latest source code. I know I was able to setup long presses in previous versions, and I can't seem to figure it out now, but apparently it's because of the bug.

I see you've added settings for the button press times in the Options tab. Will a setting of "0" leave them at previously established defaults, or is the setting actually "0"? If the latter is the case, I'm assuming that could affect the behavior too. What would you recommend for those values?

**Comment by alf45tar** [comment]
0 is zero. It is not the previous value.

Default values (after resetting to factory default) are:

Press Time              200
Double Press Time 400
Long Press Time     500
Repeat Press Time  500

You can change them in Options without resetting to factory default.

Cheers
alf45tar

**Comment by mknerr** [comment]
Okay, thank you! I put in those time values in the Options tab, and single, double, and long presses seem to be working again. But to clarify, when I updated, those were all set to zero. So, obviously, if those were pre-populated with the defaults, that would be ideal. 
I am interested to see if that is @marosell 's issue as well.

**Comment by marosell** [comment]
Not certain, but I believe the default values were empty last time I was working with it. I'll grab the latest and test it with these values if they are not the default and report back.
