### ISSUE TITLE
page refresh problem

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#340]
Add a new pedal in the action page, if you refresh the page without saving, a new pedal will be automatically added

**Comment by alf45tar** [comment]
Details of the issue is reported here https://en.wikipedia.org/wiki/Post/Redirect/Get
For PedalinoMini it is not at issue at all. Safari and Chrome warning you before proceed too.

![Screenshot 2022-05-28 at 14 20 30](https://user-images.githubusercontent.com/35426671/170825357-cb9d08a6-1b85-417a-977a-ec89efe36799.png)

![Screenshot 2022-05-28 at 14 20 56](https://user-images.githubusercontent.com/35426671/170825361-9558dc38-781e-4887-a103-5bc10a5225fa.png)
