### ISSUE TITLE
Action setting problem

### ISSUE THREAD

**Issue by bobvc133** [alf45tar/PedalinoMini#408]
Can the options in the red box be used normally? The STAR and STOP actions can only be set to ON, BUTTON, and SEND items, and the OLED display also has problems.
![Snipaste_2022-12-11_15-40-05](https://user-images.githubusercontent.com/91867813/206891975-9ec5beb3-0d0d-4dd7-afa4-ca1063b13091.png)
![微信图片_20221211154445](https://user-images.githubusercontent.com/91867813/206892093-059e4b90-cbd6-4aeb-959b-2eddcf8a6a4e.jpg)

**Comment by alf45tar** [comment]
Start, Stop and Continue are MIDI messages related to MIDI Clock. The OLED display will be fixed with the next version.
MTC Start, MTC Stop, MTC Continue, Tap, BPM+ and BPM- are related to Midi Time Code.

MIDI Clock and MTC are already implemented in the code but they is no user interface to activate/operate yet.

**Comment by bobvc133** [comment]
When will the MIDI clock and MTC function be able to be used normally? This is also a relatively important function.
